Upgrades Go + adds some linting + static checking to CI (#7)
* Adds in linting step to test

* Upgrades to go 1.19

* Adds staticcheck to builder docker image

* Adds linting to GHA

* Upgrade go modules

* Install staticcheck on GHA

* More verbose GHAs

* Fix GHA deprecation warnings

diff --git a/.github/workflows/go.yaml b/.github/workflows/go.yaml
--- a/.github/workflows/go.yaml
+++ b/.github/workflows/go.yaml
@@ -9,13 +9,26 @@ jobs:
     steps:
 
     - name: Set up Go 1.x
-      uses: actions/setup-go@v2
+      uses: actions/setup-go@v3
       with:
-        go-version: ^1.18
+        go-version: ^1.19
       id: go
 
     - name: Check out code into the Go module directory
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
+
+    - name: Install Staticcheck
+      run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.3
+
+    - name: Install Dependencies
+      run: go mod download
+
+    - name: Lint
+      run: |
+        if [ -n "$(make fmt)" ]; then
+          echo >&2 "Linting failed. Fix files listed above."
+          exit 1
+        fi
 
     - name: Test
       run: make test
